name: asset_build_time
description:
  Embeds a build time into a library and a data asset and sets it as the assets
  last modified time.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  ffi: ^2.1.3
  logging: ^1.1.1
  # native_assets_cli: ^0.7.3
  native_assets_cli:
    path: ../../../native_assets_cli/
  # native_toolchain_c: ^0.5.3
  native_toolchain_c:
    path: ../../../native_toolchain_c/

dev_dependencies:
  ffigen: ^13.0.0
  lints: ^3.0.0
  test: ^1.23.1
